-- Migration: Update Dealer's Price for Main Distribution
-- Generated from Excel Data

DO $$
DECLARE 
  main_branch_id uuid;
BEGIN
  SELECT id INTO main_branch_id FROM branches WHERE name ILIKE '%Main Distribution%' LIMIT 1;

  IF main_branch_id IS NULL THEN
    RAISE EXCEPTION 'Main Distribution branch not found';
  END IF;

  UPDATE inventory SET dealers_price = 2000 WHERE branch_id = main_branch_id AND product_name ILIKE 'NIPPON EXTREME QDU WARM YELLOW 4L';
  UPDATE inventory SET dealers_price = 690 WHERE branch_id = main_branch_id AND product_name ILIKE 'TIMEOUT BODY FILLER WITH HARDENER 4L';
  UPDATE inventory SET dealers_price = 220 WHERE branch_id = main_branch_id AND product_name ILIKE 'TIMEOUT BODY FILLER WITH HARDENER 1L';
  UPDATE inventory SET dealers_price = 800 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX SOD145 SOLVENT NAPTHA/DEGREASER 4L';
  UPDATE inventory SET dealers_price = 730 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX SOB757 HIGH GRADE URETHANE THINNER 4L';
  UPDATE inventory SET dealers_price = 900 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX MULTIPURPOSE URETHANE THINNER 4L';
  UPDATE inventory SET dealers_price = 860 WHERE branch_id = main_branch_id AND product_name ILIKE 'ROBERLO RUBBING COMPOUND 1KG';
  UPDATE inventory SET dealers_price = 100 WHERE branch_id = main_branch_id AND product_name ILIKE 'PYLOX LAZER WHITE 02';
  UPDATE inventory SET dealers_price = 100 WHERE branch_id = main_branch_id AND product_name ILIKE 'PYLOX LAZER VIOLET 20';
  UPDATE inventory SET dealers_price = 100 WHERE branch_id = main_branch_id AND product_name ILIKE 'PYLOX LAZER SKY BLUE 22';
  UPDATE inventory SET dealers_price = 100 WHERE branch_id = main_branch_id AND product_name ILIKE 'PYLOX LAZER SILVER 42';
  UPDATE inventory SET dealers_price = 100 WHERE branch_id = main_branch_id AND product_name ILIKE 'PYLOX LAZER PRIMER GRAY 145';
  UPDATE inventory SET dealers_price = 100 WHERE branch_id = main_branch_id AND product_name ILIKE 'PYLOX LAZER MATT WHITE 03';
  UPDATE inventory SET dealers_price = 100 WHERE branch_id = main_branch_id AND product_name ILIKE 'PYLOX LAZER MATT BLACK 47';
  UPDATE inventory SET dealers_price = 100 WHERE branch_id = main_branch_id AND product_name ILIKE 'PYLOX LAZER LIGHT GREEN 33';
  UPDATE inventory SET dealers_price = 175 WHERE branch_id = main_branch_id AND product_name ILIKE 'PYLOX LAZER HEAT RESISTANT SILVER 709';
  UPDATE inventory SET dealers_price = 140 WHERE branch_id = main_branch_id AND product_name ILIKE 'PYLOX LAZER GOLD 705';
  UPDATE inventory SET dealers_price = 100 WHERE branch_id = main_branch_id AND product_name ILIKE 'PYLOX LAZER GLOSS BLACK 48';
  UPDATE inventory SET dealers_price = 150 WHERE branch_id = main_branch_id AND product_name ILIKE 'PYLOX LAZER FLOURESCENT YELLOW 600';
  UPDATE inventory SET dealers_price = 150 WHERE branch_id = main_branch_id AND product_name ILIKE 'PYLOX LAZER FLOURESCENT VIOLET 604';
  UPDATE inventory SET dealers_price = 150 WHERE branch_id = main_branch_id AND product_name ILIKE 'PYLOX LAZER FLOURESCENT RED 602';
  UPDATE inventory SET dealers_price = 150 WHERE branch_id = main_branch_id AND product_name ILIKE 'PYLOX LAZER FLOURESCENT ORANGE 601';
  UPDATE inventory SET dealers_price = 150 WHERE branch_id = main_branch_id AND product_name ILIKE 'PYLOX LAZER FLOURESCENT PINK 603';
  UPDATE inventory SET dealers_price = 150 WHERE branch_id = main_branch_id AND product_name ILIKE 'PYLOX LAZER FLOURESCENT GREEN 605';
  UPDATE inventory SET dealers_price = 150 WHERE branch_id = main_branch_id AND product_name ILIKE 'PYLOX LAZER FLOURESCENT BLUE 606';
  UPDATE inventory SET dealers_price = 100 WHERE branch_id = main_branch_id AND product_name ILIKE 'PYLOX LAZER DEEP RED 17';
  UPDATE inventory SET dealers_price = 130 WHERE branch_id = main_branch_id AND product_name ILIKE 'PYLOX LAZER DISTINGUISHED SILVER 701';
  UPDATE inventory SET dealers_price = 100 WHERE branch_id = main_branch_id AND product_name ILIKE 'PYLOX LAZER CLEAR 01';
  UPDATE inventory SET dealers_price = 115 WHERE branch_id = main_branch_id AND product_name ILIKE 'PYLOX LAZER CANDYTONE RED 801';
  UPDATE inventory SET dealers_price = 100 WHERE branch_id = main_branch_id AND product_name ILIKE 'PYLOX LAZER ART YELLOW 06';
  UPDATE inventory SET dealers_price = 100 WHERE branch_id = main_branch_id AND product_name ILIKE 'PYLOX LAZER ANTI-RUST BROWN PRIMER 12';
  UPDATE inventory SET dealers_price = 20 WHERE branch_id = main_branch_id AND product_name ILIKE 'JAPAN PUTTY KNIFE #6 BLUE';
  UPDATE inventory SET dealers_price = 18 WHERE branch_id = main_branch_id AND product_name ILIKE 'JAPAN PUTTY KNIFE #4 BLUE';
  UPDATE inventory SET dealers_price = 790 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PRO UNIVERSAL BODY FILLER 4KG';
  UPDATE inventory SET dealers_price = 500 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX ALPHA HB SPRAY FILLER GRAY WITH HARDENER 1L';
  UPDATE inventory SET dealers_price = 700 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PP BUMPER PRIMER GRAY 1L';
  UPDATE inventory SET dealers_price = 2600 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA NB100 B/C BINDER 4L';
  UPDATE inventory SET dealers_price = 2000 WHERE branch_id = main_branch_id AND product_name ILIKE 'NIPPON EXTREME QDU SILVER 4L';
  UPDATE inventory SET dealers_price = 2000 WHERE branch_id = main_branch_id AND product_name ILIKE 'NIPPON EXTREME QDU GREEN 4L';
  UPDATE inventory SET dealers_price = 2000 WHERE branch_id = main_branch_id AND product_name ILIKE 'NIPPON EXTREME QDU RED 4L';
  UPDATE inventory SET dealers_price = 1850 WHERE branch_id = main_branch_id AND product_name ILIKE 'NIPPON EXTREME QDU WHITE 4L';
  UPDATE inventory SET dealers_price = 1850 WHERE branch_id = main_branch_id AND product_name ILIKE 'NIPPON EXTREME QDU BLACK 4L';
  UPDATE inventory SET dealers_price = 2000 WHERE branch_id = main_branch_id AND product_name ILIKE 'NIPPON EXTREME QDU BLUE 4L';
  UPDATE inventory SET dealers_price = 2000 WHERE branch_id = main_branch_id AND product_name ILIKE 'NIPPON EXTREME QDU YELLOW 4L';
  UPDATE inventory SET dealers_price = 2000 WHERE branch_id = main_branch_id AND product_name ILIKE 'NIPPON EXTREME QDU ORANGE 4L';
  UPDATE inventory SET dealers_price = 1500 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX EXTREME EPOXY ENAMEL WHITE WITH HARDENER 4L';
  UPDATE inventory SET dealers_price = 1500 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX EXTREME EPOXY ENAMEL BLACK W/HARDENER 4L';
  UPDATE inventory SET dealers_price = 1500 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX EXTREME EPOXY ENAMEL YELLOW WITH HARDENER 4L';
  UPDATE inventory SET dealers_price = 1500 WHERE branch_id = main_branch_id AND product_name ILIKE 'NIPPELAC ACE BRIGHT WHITE 4L';
  UPDATE inventory SET dealers_price = 1500 WHERE branch_id = main_branch_id AND product_name ILIKE 'NIPPELAC ACE JET BLACK 4L';
  UPDATE inventory SET dealers_price = 1800 WHERE branch_id = main_branch_id AND product_name ILIKE 'NIPPELAC ACE THALO GREEN 4L';
  UPDATE inventory SET dealers_price = 1800 WHERE branch_id = main_branch_id AND product_name ILIKE 'NIPPELAC ACE LEMON YELLOW 4L';
  UPDATE inventory SET dealers_price = 2500 WHERE branch_id = main_branch_id AND product_name ILIKE 'NIPPELAC ACE RED TRIPLE 8 4L';
  UPDATE inventory SET dealers_price = 1350 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA NP9700 HS 2K CLEAR WITH HARDENER 1L';
  UPDATE inventory SET dealers_price = 1150 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA NP9200 2K CLEAR WITH HARDENER 1L';
  UPDATE inventory SET dealers_price = 2550 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA NB200 BINDER';
  UPDATE inventory SET dealers_price = 900 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX 301 NAX QDU FLAT CLEAR WITH HARDENER 1L';
  UPDATE inventory SET dealers_price = 225 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAX21 URETHANE HARDENER';
  UPDATE inventory SET dealers_price = 500 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX 141 NAX MAXIMA URETHANE FD CLEAR WITH HARDENER 1L';
  UPDATE inventory SET dealers_price = 600 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX 108 CERAMIC 2K CLEAR WITH HARDENER 1L';
  UPDATE inventory SET dealers_price = 700 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-1062 QDU 040 SUPER WHITE 1L';
  UPDATE inventory SET dealers_price = 970 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-10100 NH-585 PEARL WHITE MICA 1L';
  UPDATE inventory SET dealers_price = 620 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-992 TTC BLACK NO.8 1L';
  UPDATE inventory SET dealers_price = 2100 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-990 TTC BLACK 4L';
  UPDATE inventory SET dealers_price = 620 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-990 TTC BLACK 1L';
  UPDATE inventory SET dealers_price = 1200 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-745 TTC MEDIUM SPARKLE SILVER 1L';
  UPDATE inventory SET dealers_price = 670 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-740 TTC ULTRA FINE SILVER 1L';
  UPDATE inventory SET dealers_price = 900 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-736 TTC HI-SPARKLE EXTRA COARSE 1L';
  UPDATE inventory SET dealers_price = 620 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-733 TTC SUPER FINE WHITE SILVER 1L';
  UPDATE inventory SET dealers_price = 1070 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-729 TTC HI-SPARKLE FINE SILVER 1L';
  UPDATE inventory SET dealers_price = 1550 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-728 TTC SPARKLE ORANGE METALLIC 1L';
  UPDATE inventory SET dealers_price = 1400 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-727 TTC HI-SPARKLE MIDCOARSE SILVER 1L';
  UPDATE inventory SET dealers_price = 870 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-725 TTC SPARKLE MID-COARSE SILVER 1L';
  UPDATE inventory SET dealers_price = 900 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-720 TTC SPARKLE WHITE SILVER 1L';
  UPDATE inventory SET dealers_price = 3100 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-719 TTC COARSE SILVER 4L';
  UPDATE inventory SET dealers_price = 850 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-719 TTC COARSE SILVER 1L';
  UPDATE inventory SET dealers_price = 620 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-716 TTC SPARKLE SILVER 1L';
  UPDATE inventory SET dealers_price = 620 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-715 TTC FINE SILVER 1L';
  UPDATE inventory SET dealers_price = 3000 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-712 TTC MEDIUM FINE SILVER 4L';
  UPDATE inventory SET dealers_price = 850 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-712 TTC MEDIUM FINE SILVER 1L';
  UPDATE inventory SET dealers_price = 850 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT707 HI-SPARKLE SILVER 1L';
  UPDATE inventory SET dealers_price = 620 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT706 MEDIUM COARSE SILVER 1L';
  UPDATE inventory SET dealers_price = 620 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT705 SUPER FINE SILVER 1L';
  UPDATE inventory SET dealers_price = 700 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-595 TTC CYANINE BLUE 1L';
  UPDATE inventory SET dealers_price = 650 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-557 TTC BLUE NO.9 1L';
  UPDATE inventory SET dealers_price = 900 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-556 TTC BLUE NO.8 1L';
  UPDATE inventory SET dealers_price = 680 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-555 TTC BLUE NO.7 1L';
  UPDATE inventory SET dealers_price = 620 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-550 TTC SUPER BLUE 1L';
  UPDATE inventory SET dealers_price = 1500 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-530 TTC FINE BLUE 1L';
  UPDATE inventory SET dealers_price = 800 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-490 TTC EVERGREEN 1L';
  UPDATE inventory SET dealers_price = 1020 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-410 TTC CYANINE GREEN 1L';
  UPDATE inventory SET dealers_price = 670 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-3974 QDU FLAT BLACK 1L';
  UPDATE inventory SET dealers_price = 580 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-390 TTC IRON YELLOW 1L';
  UPDATE inventory SET dealers_price = 1560 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-380 TTC SUPER YELLOW 1L';
  UPDATE inventory SET dealers_price = 1300 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-321 TTC HOSTAPERM YELLOW 1L';
  UPDATE inventory SET dealers_price = 650 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-320 TTC GOLD YELLOW 1L';
  UPDATE inventory SET dealers_price = 1800 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-305 TTC GREEN YELLOW 1L';
  UPDATE inventory SET dealers_price = 2200 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-210 TTC SUPER ORANGE 1L';
  UPDATE inventory SET dealers_price = 1900 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-196 TTC PURPLISH RED 1L';
  UPDATE inventory SET dealers_price = 850 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-192 TTC BRIGHT RED 1L';
  UPDATE inventory SET dealers_price = 560 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-190 TTC IRON RED 1L';
  UPDATE inventory SET dealers_price = 1240 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-180 TTC STRAWBERRY RED 1L';
  UPDATE inventory SET dealers_price = 1920 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT158 CINQUASIA VIOLET 1L';
  UPDATE inventory SET dealers_price = 1860 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-149 TTC DARK MAROON 1L';
  UPDATE inventory SET dealers_price = 1610 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-147 TTC THRENE RED 1L';
  UPDATE inventory SET dealers_price = 1700 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-143 TTC FLAME RED 1L';
  UPDATE inventory SET dealers_price = 2100 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-1305 TTC 211 MICA BASE 1L';
  UPDATE inventory SET dealers_price = 2650 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-1304 TTC CRYSTALLINE ORANGE 1L';
  UPDATE inventory SET dealers_price = 2650 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-1303 TTC OMEGA PEARL 1L';
  UPDATE inventory SET dealers_price = 2650 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-1301 TTC XIRALLIC BLUE MICA 1L';
  UPDATE inventory SET dealers_price = 2650 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-1300 TTC CRYSTALLINE SILVER 1L';
  UPDATE inventory SET dealers_price = 2000 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-1180 TTC OYSTER WHITE MICA 1L';
  UPDATE inventory SET dealers_price = 1120 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-1175 TTC MEDIUM FINE BLUE MICA 1L';
  UPDATE inventory SET dealers_price = 2070 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-1173 TTC EXTRA FINE WHITE MICA 1L';
  UPDATE inventory SET dealers_price = 1300 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-1172 TTC BRIGHT GREEN MICA 1L';
  UPDATE inventory SET dealers_price = 1270 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-1171 TTC ULTRA FINE BLUE MICA 1L';
  UPDATE inventory SET dealers_price = 1300 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-1167 TTC PALE GREEN MICA 1L';
  UPDATE inventory SET dealers_price = 1470 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-1166 TTC EARTH BROWN MICA 1L';
  UPDATE inventory SET dealers_price = 1170 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-1165 TTC HI-LITE RED 1L';
  UPDATE inventory SET dealers_price = 1000 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-1164 TTC BRIGHT GOLD MICA 1L';
  UPDATE inventory SET dealers_price = 1070 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-1163 TTC FINE GREEN MICA 1L';
  UPDATE inventory SET dealers_price = 1070 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-1161 TTC LAVENDER MICA 1L';
  UPDATE inventory SET dealers_price = 1000 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-1160 TTC RED COPPER MICA 1L';
  UPDATE inventory SET dealers_price = 1120 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-1159 TTC MEDIUM RUSSET MICA 1L';
  UPDATE inventory SET dealers_price = 1070 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-1158 TTC SUPER FINE COPPER MICA 1L';
  UPDATE inventory SET dealers_price = 1070 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-1157 TTC BRIGHT COPPER MICA 1L';
  UPDATE inventory SET dealers_price = 1100 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-1153 TTC SUPER RED MICA 1L';
  UPDATE inventory SET dealers_price = 1070 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-1113 TTC FINE BLUE MICA 1L';
  UPDATE inventory SET dealers_price = 3000 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-1110 TTC BRIGHT WHITE 4L';
  UPDATE inventory SET dealers_price = 970 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-1110 TTC BRIGHT WHITE 1L';
  UPDATE inventory SET dealers_price = 1070 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-1107 TTC FINE RED MICA 1L';
  UPDATE inventory SET dealers_price = 1200 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-1106 TTC PEARL BLUE MICA 1L';
  UPDATE inventory SET dealers_price = 1630 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-103 TTC OPAL 1L';
  UPDATE inventory SET dealers_price = 2180 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-100 TTC WHITE 4L';
  UPDATE inventory SET dealers_price = 600 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX NAT-1OO TTC WHITE 1L';
  UPDATE inventory SET dealers_price = 850 WHERE branch_id = main_branch_id AND product_name ILIKE 'NIPPON ACRYLIC GLOSS THINNER 4L';
  UPDATE inventory SET dealers_price = 2100 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT904 SHADOWN GREEN 1L';
  UPDATE inventory SET dealers_price = 2100 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT903 SUN GREEN 1L';
  UPDATE inventory SET dealers_price = 2100 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT807 VACANCE BLUE 1L';
  UPDATE inventory SET dealers_price = 2200 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT806 HERMES BLUE 1L';
  UPDATE inventory SET dealers_price = 2200 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT805 CUSTOM BLUE 1L';
  UPDATE inventory SET dealers_price = 2200 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT804 ORIENT BLUE 1L';
  UPDATE inventory SET dealers_price = 2200 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT803 FRESH BLUE 1L';
  UPDATE inventory SET dealers_price = 2100 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT801 CYANINE BLUE 1L';
  UPDATE inventory SET dealers_price = 2500 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT705 FLORA VIOLET 1L';
  UPDATE inventory SET dealers_price = 3500 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT704 FINE VIOLET 1L';
  UPDATE inventory SET dealers_price = 2400 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT701 FAST VIOLET 1L';
  UPDATE inventory SET dealers_price = 2600 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT607 AUTUMN RED 1L';
  UPDATE inventory SET dealers_price = 2300 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT606 GIRAFFE YELLOW 1L';
  UPDATE inventory SET dealers_price = 2500 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT604 EXTRA MAROON 1L';
  UPDATE inventory SET dealers_price = 2500 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT603 CINQUASIA BROWN 1L';
  UPDATE inventory SET dealers_price = 3000 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT602 PEGASUS MAROON 1L';
  UPDATE inventory SET dealers_price = 2500 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT601 IRON RED 1L';
  UPDATE inventory SET dealers_price = 3100 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT508 INDIAN RED 1L';
  UPDATE inventory SET dealers_price = 3500 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT507 RUBY RED 1L';
  UPDATE inventory SET dealers_price = 2500 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT506 CINQUASIA RED 1L';
  UPDATE inventory SET dealers_price = 2850 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT505 SPARK RED 1L';
  UPDATE inventory SET dealers_price = 2550 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT503 THRENE RED G 1L';
  UPDATE inventory SET dealers_price = 2500 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT501 STRONG RED 1L';
  UPDATE inventory SET dealers_price = 4350 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT405 SUN ORANGE 1L';
  UPDATE inventory SET dealers_price = 3200 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT401 MAXIM ORANGE 1L';
  UPDATE inventory SET dealers_price = 3600 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT307 EXTRA YELLOW 1L';
  UPDATE inventory SET dealers_price = 2350 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT305 NATURAL YELLOW 1L';
  UPDATE inventory SET dealers_price = 4200 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT304 GAILY YELLOW 1L';
  UPDATE inventory SET dealers_price = 2500 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT303 FINE YELLOW 1L';
  UPDATE inventory SET dealers_price = 2600 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT302 JEWEL YELLOW 1L';
  UPDATE inventory SET dealers_price = 3100 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT301 MAPICO YELLOW 1L';
  UPDATE inventory SET dealers_price = 2300 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT203 DEEP BLACK 1L';
  UPDATE inventory SET dealers_price = 1450 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT202 TINTING BLACK NP 1L';
  UPDATE inventory SET dealers_price = 1400 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT201 BLUE BLACK 1L';
  UPDATE inventory SET dealers_price = 2400 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT175 GRAPHITE 1L';
  UPDATE inventory SET dealers_price = 3800 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT172 OPAL COLOR 1L';
  UPDATE inventory SET dealers_price = 2500 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT170 OPAL COLOR LS 1L';
  UPDATE inventory SET dealers_price = 6000 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT136 METALLIC ORANGE 1L';
  UPDATE inventory SET dealers_price = 4000 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT134 METALLIC GOLD 1L';
  UPDATE inventory SET dealers_price = 1500 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT103 WHITE LS 1L';
  UPDATE inventory SET dealers_price = 6000 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT100 WHITE HS 4L';
  UPDATE inventory SET dealers_price = 1600 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT100 WHITE HS 1L';
  UPDATE inventory SET dealers_price = 7000 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT096 MICA BASE 3M CRYSTAL SILVER 1L';
  UPDATE inventory SET dealers_price = 3700 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT093 MICA BASE 5G BLUE GREEN 1L';
  UPDATE inventory SET dealers_price = 3700 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT086 MICA BASE 6B MEDIUM BLUE 1L';
  UPDATE inventory SET dealers_price = 3700 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT085 MICA BASE 4G GREEN 1L';
  UPDATE inventory SET dealers_price = 3700 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT083 MICA BASE 4R RED 1L';
  UPDATE inventory SET dealers_price = 3700 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT081 MICA BASE 3PK RUTILE RED 1L';
  UPDATE inventory SET dealers_price = 3700 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT080 MICA BASE 3G FINE GREEN 1L';
  UPDATE inventory SET dealers_price = 3700 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT079 MICA BASE 2V VIOLET 1L';
  UPDATE inventory SET dealers_price = 3700 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT078 MICA BASE 5W BRIGHT WHITE 1L';
  UPDATE inventory SET dealers_price = 3700 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT076 MICA BASE 4Y PLATINUM GOLD 1L';
  UPDATE inventory SET dealers_price = 3700 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT075 MICA BASE 3Y FINE GOLD 1L';
  UPDATE inventory SET dealers_price = 3700 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT072 MICA BASE 2W LUSTRE SATIN 1L';
  UPDATE inventory SET dealers_price = 3700 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT071 MICA BASE 5B BLUE 1L';
  UPDATE inventory SET dealers_price = 4300 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT 06M NEO MICA BASE 3AG GREEN 1L';
  UPDATE inventory SET dealers_price = 4300 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT06H NEO MICA BASE 3AB BLUE 1L';
  UPDATE inventory SET dealers_price = 4300 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT06A NEO MICA BASE 3YG YELLOW 1L';
  UPDATE inventory SET dealers_price = 7200 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT068 MICA BASE 3U RADIANT RED 1L';
  UPDATE inventory SET dealers_price = 3700 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT067 MICA BASE 2K RED BROWN 1L';
  UPDATE inventory SET dealers_price = 3700 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT066 MICA BASE 2R FINE RUSSET 1L';
  UPDATE inventory SET dealers_price = 3700 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT065 MICA BASE 3B FINE BLUE 1L';
  UPDATE inventory SET dealers_price = 3700 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT061 MICA BASE 6W FINE SATIN 1L';
  UPDATE inventory SET dealers_price = 4000 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT051 MICA BASE 2BZ BRONZE 1L';
  UPDATE inventory SET dealers_price = 3700 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT050 MICA BASE 2ST SCRAB RED 1L';
  UPDATE inventory SET dealers_price = 2700 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT033 WHITE MET. MEDIUM FINE 1L';
  UPDATE inventory SET dealers_price = 2300 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT030 WHITE MET. SNOW FINE 1L';
  UPDATE inventory SET dealers_price = 2700 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT028 HIGH SPARKLE SUPER GLAMOUR 1L';
  UPDATE inventory SET dealers_price = 2300 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT025 HIGH SPARKLE SUPER COARSE 1L';
  UPDATE inventory SET dealers_price = 2500 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT023 HIGH SPARKLE FINE 1L';
  UPDATE inventory SET dealers_price = 2300 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT012 MET. BASE FINE 1L';
  UPDATE inventory SET dealers_price = 2700 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT008 CRYSTAL SILVER COARSE 1L';
  UPDATE inventory SET dealers_price = 2700 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT006 CRYSTAL SILVER MEDIUM 1L';
  UPDATE inventory SET dealers_price = 2700 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT004 CRYSTAL SILVER COARSE 1L';
  UPDATE inventory SET dealers_price = 2700 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT003 CRYSTAL SILVER MEDIUM 1L';
  UPDATE inventory SET dealers_price = 2700 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT002 CRYSTAL SILVER FINE 1L';
  UPDATE inventory SET dealers_price = 2700 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA MT001 CRYSTAL SILVER EXTRA FINE 1L';
  UPDATE inventory SET dealers_price = 65 WHERE branch_id = main_branch_id AND product_name ILIKE 'OLD NEWS';
  UPDATE inventory SET dealers_price = 1000 WHERE branch_id = main_branch_id AND product_name ILIKE 'METALGUARD EPOXY PRIMER BLACK WITH HARDENER 4L';
  UPDATE inventory SET dealers_price = 0 WHERE branch_id = main_branch_id AND product_name ILIKE 'METALGUARD EPOXY PRIMER BLACK WITH HARDENER 1L';
  UPDATE inventory SET dealers_price = 1000 WHERE branch_id = main_branch_id AND product_name ILIKE 'METALGUARD EPOXY PRIMER GRAY WITH HARDENER 4L';
  UPDATE inventory SET dealers_price = 0 WHERE branch_id = main_branch_id AND product_name ILIKE 'METALGUARD EPOXY PRIMER GRAY WITH HARDENER 1L';
  UPDATE inventory SET dealers_price = 1000 WHERE branch_id = main_branch_id AND product_name ILIKE 'METALGUARD EPOXY PRIMER RED OXIDE WITH HARDENER 4L';
  UPDATE inventory SET dealers_price = 0 WHERE branch_id = main_branch_id AND product_name ILIKE 'METALGUARD EPOXY PRIMER RED OXIDE WITH HARDENER 1L';
  UPDATE inventory SET dealers_price = 1000 WHERE branch_id = main_branch_id AND product_name ILIKE 'METALGUARD EPOXY PRIMER WHITE WITH HARDENER 4L';
  UPDATE inventory SET dealers_price = 0 WHERE branch_id = main_branch_id AND product_name ILIKE 'METALGUARD EPOXY PRIMER WHITE WITH HARDENER 1L';
  UPDATE inventory SET dealers_price = 650 WHERE branch_id = main_branch_id AND product_name ILIKE 'NIPPON HS FILLER 1L';
  UPDATE inventory SET dealers_price = 1600 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PREMILA FF151 FLIP FLAT ADJ 1L';
  UPDATE inventory SET dealers_price = 2000 WHERE branch_id = main_branch_id AND product_name ILIKE 'NIPPON EXTREME QDU FINE SILVER 4L';
  UPDATE inventory SET dealers_price = 870 WHERE branch_id = main_branch_id AND product_name ILIKE 'NIPPON EPOXY THINNER 4L';
  UPDATE inventory SET dealers_price = 24.5 WHERE branch_id = main_branch_id AND product_name ILIKE 'EAGLE SANDPAPER 800';
  UPDATE inventory SET dealers_price = 33 WHERE branch_id = main_branch_id AND product_name ILIKE 'EAGLE SANDPAPER #80';
  UPDATE inventory SET dealers_price = 24.5 WHERE branch_id = main_branch_id AND product_name ILIKE 'EAGLE SANDPAPER 600';
  UPDATE inventory SET dealers_price = 36 WHERE branch_id = main_branch_id AND product_name ILIKE 'EAGLE SANDPAPER #60';
  UPDATE inventory SET dealers_price = 24.5 WHERE branch_id = main_branch_id AND product_name ILIKE 'EAGLE SANDPAPER 400';
  UPDATE inventory SET dealers_price = 24.5 WHERE branch_id = main_branch_id AND product_name ILIKE 'EAGLE SANDPAPER 240';
  UPDATE inventory SET dealers_price = 33 WHERE branch_id = main_branch_id AND product_name ILIKE 'EAGLE SANDPAPER 2000';
  UPDATE inventory SET dealers_price = 30 WHERE branch_id = main_branch_id AND product_name ILIKE 'EAGLE SANDPAPER 1500';
  UPDATE inventory SET dealers_price = 24.5 WHERE branch_id = main_branch_id AND product_name ILIKE 'EAGLE SANDPAPER 1200';
  UPDATE inventory SET dealers_price = 24.5 WHERE branch_id = main_branch_id AND product_name ILIKE 'EAGLE SANDPAPER 120';
  UPDATE inventory SET dealers_price = 24.5 WHERE branch_id = main_branch_id AND product_name ILIKE 'EAGLE SANDPAPER 1000';
  UPDATE inventory SET dealers_price = 30 WHERE branch_id = main_branch_id AND product_name ILIKE 'EAGLE SANDPAPER #100';
  UPDATE inventory SET dealers_price = 620 WHERE branch_id = main_branch_id AND product_name ILIKE 'DOMINO BODY FILLER WITH HARDENER 4L';
  UPDATE inventory SET dealers_price = 195 WHERE branch_id = main_branch_id AND product_name ILIKE 'DOMINO BODY FILLER WITH HARDENER 1L';
  UPDATE inventory SET dealers_price = 1570 WHERE branch_id = main_branch_id AND product_name ILIKE 'CROCO MASKING TAPE 3/4 18MM (1X64)';
  UPDATE inventory SET dealers_price = 1570 WHERE branch_id = main_branch_id AND product_name ILIKE 'CROCO MASKING TAPE 2 48MM (1X24)';
  UPDATE inventory SET dealers_price = 1570 WHERE branch_id = main_branch_id AND product_name ILIKE 'CROCO MASKING TAPE 1/2 12MM (1X96)';
  UPDATE inventory SET dealers_price = 1570 WHERE branch_id = main_branch_id AND product_name ILIKE 'CROCO MASKING TAPE 1 24MM (1X48)';
  UPDATE inventory SET dealers_price = 750 WHERE branch_id = main_branch_id AND product_name ILIKE 'NIPPON FLATTENING PASTE 1L';
  UPDATE inventory SET dealers_price = 2200 WHERE branch_id = main_branch_id AND product_name ILIKE 'NIPPON EXTREME QDU MAROON 4L';
  UPDATE inventory SET dealers_price = 2000 WHERE branch_id = main_branch_id AND product_name ILIKE 'NIPPON EXTREME QDU CINQUASIA VIOLET 4L';
  UPDATE inventory SET dealers_price = 2200 WHERE branch_id = main_branch_id AND product_name ILIKE 'NIPPON EXTREME QDU MAGENTA 4L';
  UPDATE inventory SET dealers_price = 24.5 WHERE branch_id = main_branch_id AND product_name ILIKE 'EAGLE SANDPAPER 320';
  UPDATE inventory SET dealers_price = 480 WHERE branch_id = main_branch_id AND product_name ILIKE 'TIMELESS RUBBING COMPOUND 630GRMS';
  UPDATE inventory SET dealers_price = 75 WHERE branch_id = main_branch_id AND product_name ILIKE 'TIMELESS LIQUID WAX 50ML';
  UPDATE inventory SET dealers_price = 75 WHERE branch_id = main_branch_id AND product_name ILIKE 'TIMELESS RUBBING COMPOUND SACHET';
  UPDATE inventory SET dealers_price = 1500 WHERE branch_id = main_branch_id AND product_name ILIKE 'NIPPON ULTRA 8100T FD 2K CLEAR 1L';
  UPDATE inventory SET dealers_price = 720 WHERE branch_id = main_branch_id AND product_name ILIKE 'NIPPON PREMIUM HS CLEAR W/H 1L';
  UPDATE inventory SET dealers_price = 75 WHERE branch_id = main_branch_id AND product_name ILIKE '2B PAINT ROLLER #7 W/HANDLE';
  UPDATE inventory SET dealers_price = 24.5 WHERE branch_id = main_branch_id AND product_name ILIKE 'EAGLE SANDPAPER 220';
  UPDATE inventory SET dealers_price = 1900 WHERE branch_id = main_branch_id AND product_name ILIKE 'NIPPON ULTRA 8300F CRYSTAL 2K CLEAR W/H 1L';
  UPDATE inventory SET dealers_price = 750 WHERE branch_id = main_branch_id AND product_name ILIKE 'NAX PP BUMPER PRIMER CLEAR 1L';

END $$;
