-- ============================================================
-- Sync Missing Customers from test.xlsx (Main Distribution)
-- ============================================================

DO $$ 
DECLARE
  v_main_branch_id UUID;
BEGIN
  SELECT id INTO v_main_branch_id FROM public.branches WHERE name ILIKE '%main distribution%' OR name ILIKE '%main%' LIMIT 1;
  IF v_main_branch_id IS NULL THEN
    RAISE EXCEPTION 'Could not find Main Distribution branch.';
  END IF;

  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_00001' || '-MAIN', 'APC KAUSWAGAN', 'NAT''L HIWAY KAUSWAGAN, CAGAYAN DE ORO CITY', 'MIRASOL TEVES', '0915-532-5653', '90 DAYS', v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = 'APC KAUSWAGAN' AND branch_id = v_main_branch_id);
  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_00002' || '-MAIN', 'APC AGORA', 'AGORA RD. LAPASAN, CAGAYAN DE ORO CITY', 'JUPITER SON', '0965-062-8340', '90 DAYS', v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = 'APC AGORA' AND branch_id = v_main_branch_id);
  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_00003' || '-MAIN', 'APC AGORA_ISUZU', 'LAPASAN CAGAYAN DE ORO CITY', 'ALBERT BACOR', NULL, '90 DAYS', v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = 'APC AGORA_ISUZU' AND branch_id = v_main_branch_id);
  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_00004' || '-MAIN', 'ARCHSTILE PAINT CENTER', 'CARMEN, CAGAYAN DE ORO CITY', NULL, NULL, '60 DAYS', v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = 'ARCHSTILE PAINT CENTER' AND branch_id = v_main_branch_id);
  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_00005' || '-MAIN', 'ARIES PAINT AND GENERAL MDSE. CO', 'ILIGAN CITY', NULL, NULL, '90 DAYS', v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = 'ARIES PAINT AND GENERAL MDSE. CO' AND branch_id = v_main_branch_id);
  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_00006' || '-MAIN', 'ARKO ENTERPRISES', 'UPPER MACASANDIG, CAGAYAN DE ORO CITY', NULL, NULL, '60 DAYS', v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = 'ARKO ENTERPRISES' AND branch_id = v_main_branch_id);
  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_00007' || '-MAIN', 'AXELUM RESOURCES CORP.', 'ICS BLDG. TIANO MONTALVAN ST. CAGAYAN DE ORO CITY', NULL, NULL, '45 DAYS', v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = 'AXELUM RESOURCES CORP.' AND branch_id = v_main_branch_id);
  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_00008' || '-MAIN', 'CAR CRAZY', 'ILIGAN CITY', NULL, NULL, '60 DAYS', v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = 'CAR CRAZY' AND branch_id = v_main_branch_id);
  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_00009' || '-MAIN', 'COCODERIVATIVES INC.', NULL, NULL, NULL, '60 DAYS', v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = 'COCODERIVATIVES INC.' AND branch_id = v_main_branch_id);
  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_00010' || '-MAIN', 'CYB PAINT CENTER', 'ZAMBOANGA CITY', NULL, NULL, '90 DAYS', v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = 'CYB PAINT CENTER' AND branch_id = v_main_branch_id);
  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_00011' || '-MAIN', 'ED PAINT CENTER', 'CUGMAN, CAGAYAN DE ORO CITY', NULL, NULL, 'COD', v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = 'ED PAINT CENTER' AND branch_id = v_main_branch_id);
  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_00012' || '-MAIN', 'FIX POINT C/O MNM HARDWARE', 'MOLAVE ZAMBOANGA DEL SUR', NULL, NULL, '90 DAYS', v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = 'FIX POINT C/O MNM HARDWARE' AND branch_id = v_main_branch_id);
  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_00013' || '-MAIN', 'G AND M PAINT CENTER', 'DIPOLOG CITY', NULL, NULL, '60 DAYS', v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = 'G AND M PAINT CENTER' AND branch_id = v_main_branch_id);
  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_00014' || '-MAIN', 'GOGOMAC GEN. MDSE. CORP.', 'UPTOWN, CAGAYAN DE ORO CITY', NULL, NULL, '60 DAYS', v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = 'GOGOMAC GEN. MDSE. CORP.' AND branch_id = v_main_branch_id);
  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_00015' || '-MAIN', 'GREEN HARDWARE C/O MNM HARDWARE', 'SINDANGAN, ZAMBOANGA DEL SUR', NULL, NULL, '90 DAYS', v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = 'GREEN HARDWARE C/O MNM HARDWARE' AND branch_id = v_main_branch_id);
  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_00016' || '-MAIN', 'HENRY AUTO CARE', 'TANGUB CITY', NULL, NULL, '90 DAYS', v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = 'HENRY AUTO CARE' AND branch_id = v_main_branch_id);
  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_00017' || '-MAIN', 'ICOR PAINT CENTER', 'ILIGAN CITY', NULL, NULL, '60 DAYS', v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = 'ICOR PAINT CENTER' AND branch_id = v_main_branch_id);
  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_00018' || '-MAIN', 'JAMS PAINT HAUZ', 'OZAMIS CITY', NULL, NULL, 'TERMS', v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = 'JAMS PAINT HAUZ' AND branch_id = v_main_branch_id);
  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_00019' || '-MAIN', 'J-ANN PAINT CENTER', 'LAPASAN, CAGAYAN DE ORO CITY', NULL, NULL, '30 DAYS', v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = 'J-ANN PAINT CENTER' AND branch_id = v_main_branch_id);
  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_00020' || '-MAIN', 'JAYFORD PAINTING SERVICES', 'MARANDING LANAO DEL NORTE', NULL, NULL, '90 DAYS', v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = 'JAYFORD PAINTING SERVICES' AND branch_id = v_main_branch_id);
  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_00021' || '-MAIN', 'JDE PAINT CENTER', 'VAMENTA ST. CARMEN, CAGAYAN DE ORO CITY', NULL, NULL, '90 DAYS', v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = 'JDE PAINT CENTER' AND branch_id = v_main_branch_id);
  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_00022' || '-MAIN', 'JJ PAINT CENTER', 'ZONE 4 CUGMAN, CAGAYAN DE ORO CITY', NULL, NULL, '60 DAYS', v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = 'JJ PAINT CENTER' AND branch_id = v_main_branch_id);
  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_00023' || '-MAIN', 'JOMAR LUMASAG', 'CAGAYAN DE ORO CITY', NULL, NULL, '90 DAYS', v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = 'JOMAR LUMASAG' AND branch_id = v_main_branch_id);
  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_00024' || '-MAIN', 'KIM BUILDERS', NULL, NULL, NULL, 'COD', v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = 'KIM BUILDERS' AND branch_id = v_main_branch_id);
  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_00025' || '-MAIN', 'KING V PAINT CENTER', 'PAGADIAN CITY', NULL, NULL, '60 DAYS', v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = 'KING V PAINT CENTER' AND branch_id = v_main_branch_id);
  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_00026' || '-MAIN', 'MATTEO PAINT CENTER', 'NHA, KAUSWAGAN CAGAYAN DE ORO CITY', NULL, NULL, '60 DAYS', v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = 'MATTEO PAINT CENTER' AND branch_id = v_main_branch_id);
  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_00027' || '-MAIN', 'MEGA PAINT CENTER', 'IPIL, ZAMBOANGA SIBUGAY', NULL, NULL, '90 DAYS', v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = 'MEGA PAINT CENTER' AND branch_id = v_main_branch_id);
  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_00028' || '-MAIN', 'NCCC PAINT CENTER C/0 MNM HARDWARE', 'ILIGAN CITY', NULL, NULL, '90 DAYS', v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = 'NCCC PAINT CENTER C/0 MNM HARDWARE' AND branch_id = v_main_branch_id);
  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_00029' || '-MAIN', 'NHARDWARE', 'TAGOLOAN MISAMIS ORIENTAL', NULL, NULL, '60 DAYS', v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = 'NHARDWARE' AND branch_id = v_main_branch_id);
  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_00030' || '-MAIN', 'NICE RIDE AUTO DETAILING', 'PAGADIAN CITY', NULL, NULL, 'PDC 60 DAYS', v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = 'NICE RIDE AUTO DETAILING' AND branch_id = v_main_branch_id);
  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_00031' || '-MAIN', 'ONE STAR PAINT CENTER C/O MNM HARDWARE', NULL, NULL, NULL, '90 DAYS', v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = 'ONE STAR PAINT CENTER C/O MNM HARDWARE' AND branch_id = v_main_branch_id);
  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_00032' || '-MAIN', 'PEINTOHAUZ', 'ILIGAN CITY', NULL, NULL, '90 DAYS', v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = 'PEINTOHAUZ' AND branch_id = v_main_branch_id);
  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_00033' || '-MAIN', 'REINCE PAINT CENTER', 'ILIGAN CITY', NULL, NULL, '90 DAYS', v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = 'REINCE PAINT CENTER' AND branch_id = v_main_branch_id);
  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_00034' || '-MAIN', 'SEAN AND TROY', 'ILIGAN CITY', NULL, NULL, 'PDC 90 DAYS', v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = 'SEAN AND TROY' AND branch_id = v_main_branch_id);
  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_00035' || '-MAIN', 'SHIMMER', 'TUBOD LANAO DEL NORTE', NULL, NULL, 'COD', v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = 'SHIMMER' AND branch_id = v_main_branch_id);
  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_00036' || '-MAIN', 'SINCERE HARDWARE', 'OZAMIS CITY', NULL, NULL, 'PDC 60 DAYS', v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = 'SINCERE HARDWARE' AND branch_id = v_main_branch_id);
  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_00037' || '-MAIN', 'SKYLINE PAINTS OPC', 'CAGAYAN DE ORO CITY', NULL, NULL, 'PDC 60 DAYS', v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = 'SKYLINE PAINTS OPC' AND branch_id = v_main_branch_id);
  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_00038' || '-MAIN', 'STA. FE PAINT CENTER C/O MNM HARDWARE', NULL, NULL, NULL, '90 DAYS', v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = 'STA. FE PAINT CENTER C/O MNM HARDWARE' AND branch_id = v_main_branch_id);
  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_00039' || '-MAIN', 'T&C PAINT & ELECTRICAL SUPPLY INC.', 'ILIGAN CITY', NULL, NULL, '60 DAYS', v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = 'T&C PAINT & ELECTRICAL SUPPLY INC.' AND branch_id = v_main_branch_id);
  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_00040' || '-MAIN', 'TINONG ENTERPRISES', 'BUTUAN CITY', NULL, NULL, 'PDC 90 DAYS', v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = 'TINONG ENTERPRISES' AND branch_id = v_main_branch_id);
  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_00041' || '-MAIN', 'TOMS PROFESSIONAL DETAILERS', 'ZAMBOANGA CITY', NULL, NULL, '90 DAYS', v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = 'TOMS PROFESSIONAL DETAILERS' AND branch_id = v_main_branch_id);
  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_00042' || '-MAIN', 'TRIPLE 8 PAINT HOUSE', 'ZAMBOANGA CITY', NULL, NULL, '90 DAYS', v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = 'TRIPLE 8 PAINT HOUSE' AND branch_id = v_main_branch_id);
  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_00043' || '-MAIN', 'XTRA PAINT CENTER & GEN. MDSE.', 'LAPASAN, CAGAYAN DE ORO CITY', NULL, NULL, 'PDC 60 DAYS', v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = 'XTRA PAINT CENTER & GEN. MDSE.' AND branch_id = v_main_branch_id);
  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_00044' || '-MAIN', 'YA, SHEINAH MARIE R.', 'AGUSAN, CAGAYAN DE ORO CITY', NULL, NULL, 'PDC 90 DAYS', v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = 'YA, SHEINAH MARIE R.' AND branch_id = v_main_branch_id);
  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_00045' || '-MAIN', 'ZAMBOANGA COLOR COATING', 'ZAMBOANGA CITY', NULL, NULL, '90 DAYS', v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = 'ZAMBOANGA COLOR COATING' AND branch_id = v_main_branch_id);
  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_00046' || '-MAIN', 'AUTOWORX REPAIR AND GENERAL MDSE. CO. LTD', 'KAUSWAGAN HIWAY, CDO', NULL, NULL, '90 DAYS', v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = 'AUTOWORX REPAIR AND GENERAL MDSE. CO. LTD' AND branch_id = v_main_branch_id);
  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_00047' || '-MAIN', 'JAMES PAINT CENTER', NULL, NULL, NULL, 'COD', v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = 'JAMES PAINT CENTER' AND branch_id = v_main_branch_id);
  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_00048' || '-MAIN', 'JOEM TADURA', NULL, NULL, NULL, 'COD', v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = 'JOEM TADURA' AND branch_id = v_main_branch_id);
  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_98413415' || '-MAIN', 'CANCELLED', NULL, NULL, NULL, NULL, v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = 'CANCELLED' AND branch_id = v_main_branch_id);
  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_1b5b36a4' || '-MAIN', 'KARLA', NULL, NULL, NULL, 'COD', v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = 'KARLA' AND branch_id = v_main_branch_id);
  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_ee9e2ab9' || '-MAIN', 'JONATHAN ASUNCION', NULL, NULL, NULL, 'COD', v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = 'JONATHAN ASUNCION' AND branch_id = v_main_branch_id);
  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_85758804' || '-MAIN', 'DELIVERY', NULL, NULL, NULL, NULL, v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = 'DELIVERY' AND branch_id = v_main_branch_id);
  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_a897fd9d' || '-MAIN', '7J''S PAINT CENTER', NULL, NULL, NULL, 'COD', v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = '7J''S PAINT CENTER' AND branch_id = v_main_branch_id);
  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_8645feb5' || '-MAIN', 'YABO / EZV HARDWARE', NULL, NULL, NULL, 'COD', v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = 'YABO / EZV HARDWARE' AND branch_id = v_main_branch_id);
  INSERT INTO public.customers (customer_id, name, address, contact_person, contact_number, terms, branch_id) SELECT 'CUST_62d0f4f6' || '-MAIN', 'JHING CONSTRUCTION SUPPLY', NULL, NULL, NULL, NULL, v_main_branch_id WHERE NOT EXISTS (SELECT 1 FROM public.customers WHERE name = 'JHING CONSTRUCTION SUPPLY' AND branch_id = v_main_branch_id);

END $$;
